version: 0.0
os: linux

files:
  - source: api-blsheet
    destination: /home/ec2-user/app

  - source: scripts
    destination: /home/ec2-user/scripts

hooks:
  AfterInstall:
    - location: scripts/install.sh   # ✅ FIXED
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh     # ✅ FIXED
      timeout: 300
      runas: ec2-user
