version: 0.0
os: linux

files:
  - source: api-blsheet
    destination: /home/ec2-user/app

  - source: scripts
    destination: /home/ec2-user/scripts

hooks:
  AfterInstall:
    - location: /home/ec2-user/scripts/install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: /home/ec2-user/scripts/start.sh
      timeout: 300
      runas: ec2-user
