version: 0.2

phases:
  install:
    commands:
      - cd api-blsheet    # ← make sure this line exists
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - api-blsheet/**/*
    - scripts/**/*
    - appspec.yml
  exclude-paths:
    - api-blsheet/node_modules/**/*
